// src/wc/layout.ts
class LayoutComponent extends HTMLElement {
    constructor() {
        super()
        this.attachShadow({ mode: "open" }) // Shadow DOM verwenden
    }

    connectedCallback() {
        this.render()
    }

    render() {
        // Shadow DOM-Inhalt
        this.shadowRoot!.innerHTML = /*html*/ `
            <style>
.root {
    --spacing: 0.25rem;

    position: relative;
    display: grid;
    height: 100dvh;
    grid-template-columns: 0 3rem 15rem auto;
    grid-template-rows: 3rem auto;
}

.hidden-input {
    position: fixed;
    --size: 0;
    height: var(--size);
    width: var(--size);
    appearance: none;
    opacity: 0;
}

.toggler {
    grid-column-start: 2;
}

@media (width < 64rem) {
    .toggler[for="layout-expand"] {
        display: none;
    }
}

@media (width >= 64rem) {
    .toggler[for="layout-drawer"] {
        display: none;
    }
}

.toggler > svg {
    display: inline-block;
    --size: 1em;
    width: var(--size);
    height: var(--size);
    fill: currentColor;
}

.header {
    grid-column-start: 3;
    grid-column-end: 5;
}

.side {
    overflow: auto;
}

@media (width < 64rem) {
    .side {
        translate: -100% 0;
        min-height: 100%;
        width: calc(var(--spacing) * 80);
    }

    #layout-drawer:checked ~ .side {
        position: fixed;
        z-index: 1;
        translate: 0;
    }
}

@media (width >= 64rem) {
    #layout-expand:checked ~ .side {
        grid-column-start: 2;
        grid-column-end: 4;
    }
}

.main {
    overflow: auto;
    grid-column-start: 2;
    grid-column-end: 5;
}

@media (width >= 64rem) {
    #layout-expand:checked ~ .main {
        grid-column-start: 4;
    }
}

.overlay {
    position: fixed;
    inset: 0;
    display: none;
}

@media (width < 64rem) {
    #layout-drawer:checked ~ .overlay {
        display: block;
    }
}

            </style>
            <div class="root">
                <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
                    <symbol id="bi-list" viewBox="0 0 16 16">
                        <path
                            fill-rule="evenodd"
                            d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5"
                        ></path>
                    </symbol>
                </svg>

                <input id="layout-expand" type="checkbox" class="hidden-input" />
                <input id="layout-drawer" type="checkbox" class="hidden-input" />

                <label
                    class="toggler"
                    for="layout-expand"
                    title="Toggle sidebar"
                    role="button"
                >
                    <svg class="inline-block" role="img">
                        <use xlink:href="#bi-list"></use>
                    </svg>
                </label>
                <label
                    class="toggler"
                    for="layout-drawer"
                    title="Toggle sidebar"
                    role="button"
                >
                    <svg class="inline-block" role="img">
                        <use xlink:href="#bi-list"></use>
                    </svg>
                </label>
                <header class="header">Header</header>
                <div class="side"><slot name="side"></slot></div>
                <main class="main"><slot></slot></main>
                <label
                    aria-label="close sidebar"
                    for="layout-drawer"
                    class="overlay"
                ></label>
            </div>
        `
    }
}

// Web Component registrieren
customElements.define("my-layout", LayoutComponent)

// src/components/layout.tsx
import clsx from "clsx"

export interface LayoutProps {
	children?: React.ReactNode
	sideChildren?: React.ReactNode
	rootClass?: string
	togglerClass?: string
	sideClass?: string
	contentClass?: string
	drawerClass?: string
}

export default function Layout({
	children,
	sideChildren,
	rootClass = "bg-secondary-50 dark:bg-secondary-950",
	togglerClass = "btn m-1",
	sideClass = "transition-transform duration-300 ease-out will-change-transform dark:max-lg:bg-secondary-900 max-lg:bg-white max-lg:shadow-2xl",
	contentClass = "dark:text-secondary-400 border-secondary-200 dark:bg-secondary-900 dark:border-secondary-800 mx-1 mb-1 rounded-md border bg-white shadow-sm",
	drawerClass = "bg-secondary-950/50"
}: LayoutProps) {
	return (
		<div
			className={clsx(
				"root relative grid h-dvh grid-cols-[0_3rem_15rem_auto] grid-rows-[3rem_auto]",
				rootClass
			)}
		>
			<svg xmlns="http://www.w3.org/2000/svg" style={{ display: "none" }}>
				<symbol id="bi-list" viewBox="0 0 16 16">
					<path
						fill-rule="evenodd"
						d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5"
					></path>
				</symbol>
			</svg>

			<input
				id="layout-expand"
				type="checkbox"
				className="hidden-input peer/expand fixed h-0 w-0 appearance-none opacity-0"
			/>
			<input
				id="layout-drawer"
				type="checkbox"
				className="hidden-input peer/drawer fixed h-0 w-0 appearance-none opacity-0"
			/>

			<label
				className={clsx(
					"toggler col-start-2 max-lg:hidden",
					togglerClass
				)}
				htmlFor="layout-expand"
				title="Toggle sidebar"
				role="button"
			>
				<svg
					className="inline-block size-[1em] fill-current"
					role="img"
				>
					<use xlinkHref="#bi-list" />
				</svg>
			</label>
			<label
				className={clsx("toggler col-start-2 lg:hidden", togglerClass)}
				htmlFor="layout-drawer"
				title="Toggle sidebar"
				role="button"
			>
				<svg
					className="inline-block size-[1em] fill-current"
					role="img"
				>
					<use xlinkHref="#bi-list" />
				</svg>
			</label>
			<header className="header col-start-3 col-end-5">Header</header>
			<div
				className={clsx(
					"side overflow-auto peer-checked/expand:lg:col-start-2 peer-checked/expand:lg:col-end-4",
					"max-lg:-translate-x-full max-lg:peer-checked/drawer:fixed max-lg:peer-checked/drawer:translate-x-0",
					"max-lg:min-h-full max-lg:w-80 max-lg:peer-checked/drawer:z-1",
					sideClass
				)}
			>
				{sideChildren}
			</div>
			<main
				className={clsx(
					"main overflow-auto",
					"col-start-2 col-end-5 peer-checked/expand:lg:col-start-4",
					contentClass
				)}
			>
				{children}
			</main>
			<label
				aria-label="close sidebar"
				htmlFor="layout-drawer"
				className={clsx(
					"overlay fixed inset-0 hidden max-lg:peer-checked/drawer:block",
					drawerClass
				)}
			/>
		</div>
	)
}
